### ISSUE TITLE
Add package support to Chocolatey

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-cli#126]
**Is your feature request related to a problem? Please describe.**
Add support to install `jcli` with Chocolatey

**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by digitalcoyote** [comment]
I'd be willing to create/maintain a package for Chocolatey.

**Comment by LinuxSuRen** [comment]
@digitalcoyote Thanks very much! Please tell us if you need any kind of help.

**Comment by digitalcoyote** [comment]
I just pushed the package to my AU repo, so it should publish to Chocolatey in a few minutes. If you create a Chocolatey account, I can add you as a maintainer (gives basic management rights such as delisting problematic versions). 

It will probably take a week or two to go through moderation.

**Comment by LinuxSuRen** [comment]
I cannot found it. Here's [the link](https://chocolatey.org/packages?q=jenkins#packages-results).

**Comment by LinuxSuRen** [comment]
well done @digitalcoyote

**Comment by LinuxSuRen** [comment]
@digitalcoyote My account is `linuxsuren`. By the way, I didn't find it from [here](https://chocolatey.org/packages).

**Comment by digitalcoyote** [comment]
I added you as a maintainer. It's still in review, so it won't be publicly listed yet. You have to go directly to the page to see it and to install it you must explicitly request the package with the specific version. Once it is approved, it will be available publicly without the need for knowing the version/URL to access the package.

**Comment by LinuxSuRen** [comment]
Got it. Let's just wait for it. [Once it approved](https://chocolatey.org/packages/jcli), we can close this issue.

**Comment by LinuxSuRen** [comment]
I was wondering how can we push this forward.

**Comment by digitalcoyote** [comment]
So, I found out why it was showing up with so many false positives about viruses and I think I can get this pushed through now as long as there is an issue created to track it. I'll try to get that started after work today.

https://golang.org/doc/faq#virus

**Comment by LinuxSuRen** [comment]
I think this issue was done. Thank you @digitalcoyote for your effort.
