### ISSUE TITLE
Panic when running in a new computer

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-cli#147]
**Describe the bug**
The program is panic.

**To Reproduce**
1. Find a new computer
2. download and install jcli
3. execute `jcli`

**Expected behavior**
No panic happen.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Version v0.0.19

**Additional context**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13a9859]

goroutine 1 [running]:
github.com/jenkins-zh/jenkins-cli/app/cmd.getCurrentJenkins(...)
	/Users/mac/IdeaProjects/Github/jenkins-zh/jenkins-cli/app/cmd/config.go:108
github.com/jenkins-zh/jenkins-cli/app/cmd.getCurrentJenkinsFromOptions(0x40)
	/Users/mac/IdeaProjects/Github/jenkins-zh/jenkins-cli/app/cmd/root.go:75 +0x39
github.com/jenkins-zh/jenkins-cli/app/cmd.getCurrentJenkinsFromOptionsOrDie(0x1520060)
	/Users/mac/IdeaProjects/Github/jenkins-zh/jenkins-cli/app/cmd/root.go:83 +0x26
github.com/jenkins-zh/jenkins-cli/app/cmd.glob..func37(0x18215c0, 0xc0000ee580, 0x0, 0x1)
	/Users/mac/IdeaProjects/Github/jenkins-zh/jenkins-cli/app/cmd/root.go:31 +0x99
github.com/spf13/cobra.(*Command).execute(0x18215c0, 0xc00000c090, 0x1, 0x1, 0x18215c0, 0xc00000c090)
	/Users/mac/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x18215c0, 0x148a313, 0x1, 0x0)
	/Users/mac/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mac/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-zh/jenkins-cli/app/cmd.Execute()
	/Users/mac/IdeaProjects/Github/jenkins-zh/jenkins-cli/app/cmd/root.go:46 +0x32
main.main()
	/Users/mac/IdeaProjects/Github/jenkins-zh/jenkins-cli/main.go:8 +0x20
```

**Comment by yJunS** [comment]
`icli` ?

**Comment by yJunS** [comment]
There is no error information in the current version already
#129 fixed it already
![image](https://user-images.githubusercontent.com/20575981/64589705-54c36900-d3d8-11e9-924c-4ed9d732a31e.png)
![image](https://user-images.githubusercontent.com/20575981/64589837-b2f04c00-d3d8-11e9-8981-e78b68ac35db.png)

**Comment by LinuxSuRen** [comment]
It's true. I forgot this. And thanks for your remind.

**Comment by HelonLee135** [comment]
这还而已使用go跑的么

**Comment by HelonLee135** [comment]
兄弟能不能让我看看配置，我好像填少了。我今天才发现这个工具，看起来挺好用的，我现在连jenkins 都超时 
Error: Get "https://jenkins.examplexxx.com/items/list?name=&type=&start=0&limit=50&parent=": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by LinuxSuRen** [comment]
Please edit the config first via `jcli config edit`

See also https://github.com/jenkins-zh/jenkins-cli/issues/737#issuecomment-1354589817
