### ISSUE TITLE
Run "jcli -v" command haven't shown the version information when no config file

### ISSUE THREAD

**Issue by yJunS** [jenkins-zh/jenkins-cli#166]
**Describe the bug**
Run "jcli -v" command haven't shown the version information when no configuration file

**To Reproduce**
1. Run `jcli -v` when I first install or no configuration file
2. See error

**Expected behavior**
I think the version information should be displayed even if there is no configuration file.

**Screenshots**
![image](https://user-images.githubusercontent.com/20575981/65672969-85fc9400-e07c-11e9-83e5-48168e6de0bf.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Command Tool: powshell
 - Version: v0.0.20

**Additional context**
none.

**Comment by LinuxSuRen** [comment]
@zirmax Cool, so I assign this to you. And welcome!

**Comment by yJunS** [comment]
Cool

**Comment by zirmax** [comment]
Should the "no config file found" error still be thrown, if only the `-v` flag was given, or should it exit gracefully?

**Comment by LinuxSuRen** [comment]
IMO, it's necessary only when one command needs the config file. So, I agree with that no `no config file found` errors with the flag `-v`.
