### ISSUE TITLE
Add support to update all plugins

### ISSUE THREAD

**Issue by sebawo** [jenkins-zh/jenkins-cli#226]
**Is your feature request related to a problem? Please describe.**
Right now users needs to select plugin to updates one by one

**Describe the solution you'd like**
Add a flag to update all plugins

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LinuxSuRen** [comment]
It's a great suggestion! Thanks @sebawo . We need to consider providing two more options for this command. They are 'all' and 'compatible'. The usage might like this:

`jcli plugin upgrade --all`

`jcli plugin upgrade --compatible`

And, if you're interested in contributing to this feature, please let me know. So I can assign this to you.
