### ISSUE TITLE
描述文件里超链接地址失效

### ISSUE THREAD

**Issue by Sanmejie** [jenkins-zh/jenkins-cli#234]
![image](https://user-images.githubusercontent.com/40269911/68652071-ad8fb900-0563-11ea-810a-895ea07f8aca.png)

**Comment by Sanmejie** [comment]
又能下载了。

**Comment by LinuxSuRen** [comment]
你的这个截图感觉像是旧的。
![image](https://user-images.githubusercontent.com/1450685/68652254-019a9d80-0564-11ea-8bc0-63457449df96.png)

**Comment by Sanmejie** [comment]
https://github.com/linuxsuren/jenkins-cli/releases/latest/download/jcli-windows-386.tar.gz这个链接失效了，我是从testhome文章链接到项目的。 testhome文章---https://testerhome.com/topics/20313

**Comment by Sanmejie** [comment]
![image](https://user-images.githubusercontent.com/40269911/68652899-7ae6c000-0565-11ea-9466-f569bda69a7b.png)

**Comment by LinuxSuRen** [comment]
非常感谢反馈问题，已经修改了。

**Comment by LinuxSuRen** [comment]
在使用过的过程中，有任何问题，欢迎提出来。

**Comment by Sanmejie** [comment]
> 在使用过的过程中，有任何问题，欢迎提出来。

好的
