### ISSUE TITLE
job build --param support key-value format param

### ISSUE THREAD

**Issue by menggya** [jenkins-zh/jenkins-cli#238]
like jcli job build XXXX   --param FLASH=NO --param  CBN=666  --param VER=$ver  -b,so will don't  need to modify json file every time

**Comment by LinuxSuRen** [comment]
In order to keep it back compatible, I invest a new parameter for it. Usage:
`jcli job build --param-entry key=value`
But it only supports one type of parameter which is string.

I'd like to hear more feedback from you @menggya.
