### ISSUE TITLE
jcli job search --all , search with empty parameter return something wrong 

### ISSUE THREAD

**Issue by cooka** [jenkins-zh/jenkins-cli#279]
**Describe the bug**
`jcli job search --all ` , with empty filter string , should at least return random jobs, but returned something wrong, like users , non-existed jobs? 

**To Reproduce**

`jcli job search --all `

```
 $ jcli job search --all  --max 1000 | head
{
  "Suggestions": [
    {
      "Name": "1"
    },
    {
      "Name": "log"
    },
    {
      "Name": "123"
$ jcli job  build 1
? Are you sure to build job 1 Yes
Error: not found resources
Usage:
  jcli job build <jobName> [flags] ...
```

**Expected behavior**
should return jobs actually listed in jenkins dashboard. 

**Desktop (please complete the following information):**

```
jcli -v
Jenkins CLI (jcli) manage your Jenkins
Version: v0.0.23
Commit: f925117
```

**Additional context**
还是希望能有个 job list 命令, 更直观些.
and I'd hope that there's a `job list` command, just like `plugin list`, which is more intuitive .

**Comment by LinuxSuRen** [comment]
Thanks for your report. There isn't a perfect API for it currently. This should be an enhancement instead of a bug. We'll improve it.
