### ISSUE TITLE
open /tmp/logs: permission denied

### ISSUE THREAD

**Issue by 1179325921** [jenkins-zh/jenkins-cli#306]
**Describe the bug**
When I used kinkins-cli /client, I ran into a file permission problem

**To Reproduce**
1. go get github.com/jenkins-zh/jenkins-cli 
2. import  "github.com/jenkins-zh/jenkins-cli/client"
3. go run main.go

**Expected behavior**
panic: couldn't open sink "/tmp/logs": open /tmp/logs: permission denied

**Screenshots**
![image](https://user-images.githubusercontent.com/39483844/72066346-49973000-331b-11ea-86d1-79fbd41e4b41.png)

**Desktop (please complete the following information):**
 - OS: centos 7.6
 - Command Tool [e.g. cmd]
 - Version [e.g. v0.0.16]

**Additional context**
It looks as if /util/logger.go InitLogger method initializes the log to specify the directory "/tmp/logs", and I'm a Linux user who is a worker and has no permissions. Is this log directory customizable

**Comment by LinuxSuRen** [comment]
Thanks for reporting this issue. The output to the log file already been removed from [here](https://github.com/jenkins-zh/jenkins-cli/commit/a28c5707d7362e53467cfd33939ec11ddecd1161#diff-e402604e98084435e08a7a8193bb9228R14).
