### ISSUE TITLE
 No config file found.

### ISSUE THREAD

**Issue by salley-x** [jenkins-zh/jenkins-cli#318]
PS C:\Users\salley> jcli center mirror
2020/02/09 11:23:53 No config file found.
2020/02/09 11:23:53 Cannot found Jenkins by

Windows 10
war

**Comment by LinuxSuRen** [comment]
Thanks for reporting this. Please run the following diagnose command to get some hints:
`jcli center mirror --doctor`

**Comment by LinuxSuRen** [comment]
Have you resolved this problem?

**Comment by lp8608** [comment]
详细点的使用文档有吗？官网上写的太笼统了，我翻了一遍问题列表，还是遇到好多问题。
比如添加了配置文件后不管输入啥命令都是
C:\Users\lipengak>jcli plugin list
2020/02/17 22:02:16 Cannot found Jenkins by

**Comment by LinuxSuRen** [comment]
你的配置文件是在：`C:\Users\lipengak\.jenkins-cli.yaml` 吗？提示是说没有找到配置文件。

**Comment by lp8608** [comment]
是的，
另外文档中应该注明下：在windows下自动生成一个配置文档模板需要手动保存到C:\Users\lipengak\.jenkins-cli.yaml，否则还是找不到配置文件。

**Comment by LinuxSuRen** [comment]
> 注明下：在windows下自动生成一个配置文档模板需要手动保存到C:\Users\lipengak.jenkins-cli.yaml，否则jcli找不到配置文件，开始在这

感谢反馈。有了这个配置文件还是报错吗？应该是可以了的。

**Comment by lp8608** [comment]
是的，有了这个配置文件后，报错是2020/02/17 22:02:16 Cannot found Jenkins by ，之前是config找不到

**Comment by LinuxSuRen** [comment]
> 是的，有了这个配置文件后，报错是2020/02/17 22:02:16 Cannot found Jenkins by ，之前是config找不到

贴一下你的配置文件，感觉是配置有问题

**Comment by lp8608** [comment]
current: yourServer
language: ""
jenkins_servers:
- name: 45
  url: http://10.0.5.45:8080/
  username: jenkins
  token: root
  proxy: ""
  proxyAuth: ""
  insecureSkipVerify: true
  description: ""
preHooks: []
postHooks: []
pluginSuites: []
mirrors:
- name: default
  url: http://mirrors.jenkins.io/
- name: tsinghua
  url: https://mirrors.tuna.tsinghua.edu.cn/jenkins/
- name: huawei
  url: https://mirrors.huaweicloud.com/jenkins/
- name: tencent
  url: https://mirrors.cloud.tencent.com/jenkins/

**Comment by LinuxSuRen** [comment]
`current` 代表当前操作的Jenkins的配置，你的配置里，只有一个`name: 45`，执行下面的命令应该就好了：
`jcli config select 45`

**Comment by lp8608** [comment]
感谢，可以了

**Comment by LinuxSuRen** [comment]
配置文件格式检查的功能还没完成，到时候就会容易点了
