### ISSUE TITLE
jcli cannot use jcli doc without .jenkins-jcli.yaml file

### ISSUE THREAD

**Issue by yJunS** [jenkins-zh/jenkins-cli#374]
**Describe the bug**
`jcli` cannot use `jcli doc` without `.jenkins-jcli.yaml` file

**To Reproduce**

**Expected behavior**
Whether you have the `.jenkins-jcli.yaml` file or not, you can use `jcli doc`

**Screenshots**
![image](https://user-images.githubusercontent.com/20575981/78562500-0aaa4500-784c-11ea-8499-c3b10a3dbb2c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Version: v0.0.27

**Additional context**
nothing

**Comment by LinuxSuRen** [comment]
Thanks for reporting this issue.
