### ISSUE TITLE
Add MacPorts support

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-cli#402]
see also https://www.macports.org/

**Comment by harens** [comment]
Hi there 👋 

Just to let you know that I've been maintaining a portfile on MacPorts for Jenkins CLI for the last 5 months.

You can see my previous updates [here](https://github.com/macports/macports-ports/pulls?q=jenkins-cli), and the project page [here](https://ports.macports.org/port/jenkins-cli/summary). You might find it useful to document this.

Let me know if you have any questions, and I'd be happy to answer them.

All the best,
Haren

[![Packaging status](https://repology.org/badge/vertical-allrepos/jenkins-cli.svg)](https://repology.org/project/jenkins-cli/versions)

**Comment by LinuxSuRen** [comment]
hi @harens, so surprised to see that you've done it. Thanks very much for your effort. Consider that you helped us to do it. I'm wondering if you willing to record it [#other-package-managers](https://github.com/jenkins-zh/jenkins-cli#other-package-managers)
