### ISSUE TITLE
Update failed by homebrew tools

### ISSUE THREAD

**Issue by yJunS** [jenkins-zh/jenkins-cli#471]
**Describe the bug**
Update failed by homebrew tools

**To Reproduce**
1. brew upgrade jcli
2.see `Your CLT does not support macOS 11.0. It is either outdated or was modified.`

**Expected behavior**
updated success

**Screenshots**
![image](https://user-images.githubusercontent.com/20575981/99893065-c96d8500-2cb6-11eb-9670-feb34d712835.png)

**Desktop (please complete the following information):**
 - OS: mscOS Big Sur Version 11.0.1
 - Command Tool: bash
 - Version v0.0.30 -> v0.0.31

**Additional context**
I think caused by the updated macOS Big Sur

**Comment by LinuxSuRen** [comment]
I'm not sure why it is. It sounds like a compatible issue. Have ever try download jcli via curl?

For example:
```
curl -L https://github.com/jenkins-zh/jenkins-cli/releases/latest/download/jcli-darwin-amd64.tar.gz|tar xzv
```

**Comment by yJunS** [comment]
I already try it. but it's also can't use.

**Comment by yJunS** [comment]
I already fix it. 

```
$ sudo rm -rf /Library/Developer/CommandLineTools
 
$ sudo xcode-select --install

$ brew install jcli
```

That's ok.

**Comment by LinuxSuRen** [comment]
So, I guess the problem does not come from jcli. We can close t this issue if it's true.

**Comment by yJunS** [comment]
Yeah, I think maybe it's the macOS Big Sur system updated question
