### ISSUE TITLE
can not run on big sure

### ISSUE THREAD

**Issue by spacexnasa** [jenkins-zh/jenkins-cli#493]
~/Downloads/jcli-darwin-amd64]$ ./jcli --help
Killed: 9

~/Downloads/jcli-darwin-amd64]$ ./jcli 
Killed: 9

big sur intel

**Comment by LinuxSuRen** [comment]
Thanks for reporting this issue. Unfortunately I don't have a big sur. I was wondering if you can help me to do some tests if you have a Golang environment. Please try the following command in the root directory of this project:

`make`

Then, please comment them if there's anything goes wrong.

**Comment by spacexnasa** [comment]
> Thanks for reporting this issue. Unfortunately I don't have a big sur. I was wondering if you can help me to do some tests if you have a Golang environment. Please try the following command in the root directory of this project:
> 
> `make`
> 
> Then, please comment them if there's anything goes wrong.

thanks for your reply

go version 

go version go1.15.5 darwin/amd64



 ~/Downloads/jenkins-cli]$ make 
go fmt ./util/...
go fmt ./client/...
go fmt ./app/...
gofmt -s -w .
go vet ./...
export GO111MODULE=on
export GOPROXY=https://goproxy.io
go mod tidy
go: downloading gopkg.in/src-d/go-git-fixtures.v3 v3.5.0
go: downloading github.com/alcortesm/tgz v0.0.0-20161220082320-9c5fe88206d7
GO111MODULE=on CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/jenkins-zh/jenkins-cli/app.version=dev-v0.0.32 -X github.com/jenkins-zh/jenkins-cli/app.commit=2c02571 -X github.com/jenkins-zh/jenkins-cli/app.date=2020-12-05" -o bin/darwin/jcli 
chmod +x bin/darwin/jcli
rm -rf jcli && ln -s bin/darwin/jcli jcli


look like no problem

**Comment by LinuxSuRen** [comment]
The problem might caused by [upx](https://github.com/upx/upx). Please try to compress it via `upx bin/darwin/jcli`. Then run it again. Let's see if it still is ok.

Install upx via `brew install upx`

**Comment by spacexnasa** [comment]
> upx bin/darwin/jcli

upx bin/darwin/jcli
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  20766936 ->  10063888   48.46%   macho/amd64   jcli                          

Packed 1 file.

**Comment by LinuxSuRen** [comment]
Does it work well after compressed by ups?

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："space "<notifications@github.com&gt;;
发送时间：2020年12月6日(星期天) 上午10:29
收件人："jenkins-zh/jenkins-cli" <jenkins-cli@noreply.github.com&gt;;
抄送："Zhao Xiaojie "<rick@jenkins-zh.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [jenkins-zh/jenkins-cli] can not run on big sure (#493)
-----------------------------------

 

  
upx bin/darwin/jcli
  
upx bin/darwin/jcli
 Ultimate Packer for eXecutables
 Copyright (C) 1996 - 2020
 UPX 3.96        Markus Oberhumer, Laszlo Molnar &amp; John Reiser   Jan 23rd 2020
     File size         Ratio      Format      Name  
 
20766936 -&gt;  10063888   48.46%   macho/amd64   jcli
 
Packed 1 file.

**Comment by spacexnasa** [comment]
> Does it work well after compressed by ups?
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："space "<notifications@github.com&gt;; 发送时间：2020年12月6日(星期天) 上午10:29 收件人："jenkins-zh/jenkins-cli" <jenkins-cli@noreply.github.com&gt;; 抄送："Zhao Xiaojie "<rick@jenkins-zh.cn&gt;;"Comment "<comment@noreply.github.com&gt;; 主题：Re: [jenkins-zh/jenkins-cli] can not run on big sure (#493) ----------------------------------- upx bin/darwin/jcli upx bin/darwin/jcli Ultimate Packer for eXecutables Copyright (C) 1996 - 2020 UPX 3.96 Markus Oberhumer, Laszlo Molnar &amp; John Reiser Jan 23rd 2020 File size Ratio Format Name 20766936 -&gt; 10063888 48.46% macho/amd64 jcli Packed 1 file. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

yes,can work,but still cann't work by brew install jcli

**Comment by LinuxSuRen** [comment]
It seems that the command completion is not working. How about just run a simple command: `jcli --help`? Does it still be killed?

About the command completion part, you can get the description via: `jcli completion -h`

**Comment by spacexnasa** [comment]
> It seems that the command completion is not working. How about just run a simple command: `jcli --help`? Does it still be killed?
> 
> 
> 
> About the command completion part, you can get the description via: `jcli completion -h`
no this jcli  command
it's seem  installed successful,but actually not

**Comment by LinuxSuRen** [comment]
I don't have that environment yet. I was wondering if you can help to fix this.

**Comment by spacexnasa** [comment]
> I don't have that environment yet. I was wondering if you can help to fix this.

ok,i will test tomorrow

**Comment by spacexnasa** [comment]
> > I don't have that environment yet. I was wondering if you can help to fix this.
> 
> ok,i will test tomorrow

still can not work,i reboot my laptop,i have not install bash_completion.sh,because i have bash-completion@2 ✔,

**Comment by LinuxSuRen** [comment]
bash_completion is not necessary. It's optinal.

**Comment by LinuxSuRen** [comment]
I tried to compile this by:
```
go version go1.15.2 darwin/amd64
UPX 3.96
```
It works for big sur.

**Comment by spacexnasa** [comment]
maybe system problem,now has been worked finally

**Comment by LinuxSuRen** [comment]
Have you try to use the latest one? https://github.com/jenkins-zh/jenkins-cli/releases/tag/v0.0.35

If not, you can upgrade it via: `jcli version upgrade -t 8`
