### ISSUE TITLE
insecureSkipVerify Ignored by "job" subcommand while working for "credential"

### ISSUE THREAD

**Issue by sempervictus** [jenkins-zh/jenkins-cli#504]
**Describe the bug**
When running against a Jenkins API behind a self-signed Nginx TLS proxy, some subcommands work, and some do not.
For instance, `jcli computer list` and `jcli credential lsit` are fine, but `jcli user list` produces `Unable to connect to the server: x509: certificate signed by unknown authority` along with `jcli job...` subcommands

**To Reproduce**
1. Create a self-signed TLS proxy in front of jenkins
2. Build from 59ac777b using `make release`
3. Configure the YAML file with a valid `insecureSkipVerify` TLS configuration for the proxy in step 1
4. Run commands in description

**Expected behavior**
Everything works with self-signed/bad certs

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Command Tool: `jcli`
 - Version: 0.0.32 (59ac777b)

**Comment by LinuxSuRen** [comment]
Thanks for reporting this.

**Comment by LinuxSuRen** [comment]
So you mean the field `insecureSkipVerify` just is not working for some sub-commands. Right?

**Comment by sempervictus** [comment]
Affirmative

**Comment by sempervictus** [comment]
Still happening as of today's build:
```
$ jcli version
Version: dev-v0.0.34
Last Commit: 44013ea
Build Date: 2021-02-08
$ jcli computer list
DisplayName NumExecutors Description             Offline
master      16           the master Jenkins node no
$ jcli  user list
Unable to connect to the server: x509: certificate signed by unknown authority
```

**Comment by LinuxSuRen** [comment]
hi @sempervictus , thanks for reporting. I will try my best to dig it once I have free time.

**Comment by sempervictus** [comment]
Thank you @LinuxSuRen - tool seems very handy for how we work, but the fact that we keep everything beyond the edge and using self-signed fairly often is definitely a show stopper right now.

**Comment by yJunS** [comment]
Hi @sempervictus , I'm fixed the bug, and I already pull request to #530  , you can help me test this PR if you have free time

**Comment by sempervictus** [comment]
Thanks @yJunS - seems to work now. Still need to figure out the `jobs` subcommand (`jcli jobs search anything` just tells me i'm using it incorrectly, same with `--name anything`)

**Comment by yJunS** [comment]
I see this question looks like caused by API is invalid

**Comment by yJunS** [comment]
@sempervictus  The command needs a plugin, Maybe you can try to install the plugin `pipeline-restful-api`,  and the command `jcli job search --doctor` can show the context

**Comment by sempervictus** [comment]
Thank you - that did it.
One minor note - it doesnt seem to auto-convert spaces from `jcli job log "a job with spaces"` to using `%20` which might confuse users.

Thanks for resolving this.

**Comment by LinuxSuRen** [comment]
hi @sempervictus , the fix already in the next release [v0.0.35](https://github.com/jenkins-zh/jenkins-cli/releases/tag/v0.0.35)

**Comment by sempervictus** [comment]
Thank you @LinuxSuRen

**Comment by LinuxSuRen** [comment]
> Thank you @LinuxSuRen

No worries. Glad to help you.
