### ISSUE TITLE
How to config jenkins Pipeline Job  details ?

### ISSUE THREAD

**Issue by oldthreefeng** [jenkins-zh/jenkins-cli#510]
**Is your feature request related to a problem? Please describe.**

Many times we want to add or fix  an parametes to an job.  Job may hava many parametes. A prodcution has many jobs . adding or fixing a parametes  is a repeating work and useless.  

**Describe the solution you'd like**

jcli  job parametes fix or add  an map like  

--stringParas   env=qa 
--stringParas    port=3212  
--passwrodPara xxx=xxx

**Describe alternatives you've considered**

**Additional context**

Noting

**Comment by LinuxSuRen** [comment]
hi @oldthreefeng , I was wondering if you'd like to help to test #513. Let's see if it can help you out of the repeating work.

**Comment by oldthreefeng** [comment]
wow, thank you for your help~ . i will try it ~

**Comment by LinuxSuRen** [comment]
Please don't forget the install the latest of [pipeline-restful-api-plugin](https://github.com/jenkinsci/pipeline-restful-api-plugin/)
