### ISSUE TITLE
job build not work

### ISSUE THREAD

**Issue by k8scat** [jenkins-zh/jenkins-cli#558]
**Describe the bug**
`job build` command not work correctly, show me `Error: not found resources`.

full command here
```bash
jcli job build job_1/job_2/job_3/job_to_run -b
```

**To Reproduce**
Desc above.

**Comment by LinuxSuRen** [comment]
Have you try to use this format: `jcli job build -b job/testfkznq/job/111/job/master/`

You can get the path via command:
```
jcli job search
Name               DisplayName                        Type                       URL
init-job           init-job                           WorkflowJob                job/init-job/
testfkznq          testfkznq                          Folder                     job/testfkznq/
111                Zhao Xiaojie / private             WorkflowMultiBranchProject job/testfkznq/job/111/
master             master                             WorkflowJob                job/testfkznq/job/111/job/master/
```

**Comment by k8scat** [comment]
Okk, I got it, thank you very much!

**Comment by LinuxSuRen** [comment]
Anyway, the natural way might be like: `jcli job build job_1/job_2/job_3/job_to_run -b`

**Comment by k8scat** [comment]
Yes, I known now, but there is not any information to tell me to do that like you said, even the official doc.

**Comment by LinuxSuRen** [comment]
Got it.
