### ISSUE TITLE
Provide convenient way for communicating with KubeSphere as external Jenkins 

### ISSUE THREAD

**Issue by JohnNiang** [jenkins-zh/jenkins-cli#579]
**Is your feature request related to a problem? Please describe.**
Provide convenient way for communicating with KubeSphere as external Jenkins.

**Additional context**
Many users try to integrate external Jenkins into KubeSphere with many sophisticated and error-prone steps. So we could provide an easy way to achieve that.

**Comment by LinuxSuRen** [comment]
I'd suggest that having this feature in [jcli-ks-plugin](https://github.com/LinuxSuRen/jcli-ks-plugin) instead of [jenkins-cli](https://github.com/jenkins-zh/jenkins-cli/). I'll move this issue to the appropriate one.

**Comment by LinuxSuRen** [comment]
It looks like we cannot move issues across GitHub org.

**Comment by JohnNiang** [comment]
Alright.
