### ISSUE TITLE
the current user has not permission, code 403

### ISSUE THREAD

**Issue by rockwang465** [jenkins-zh/jenkins-cli#594]
**Describe the bug**
My use of GetJob and Log func is normal, but use BuildWithParams func return " the current user has not permission, code 403".  

**To Reproduce**
1.Define my Jenkins information  
```
func NewJenkinsJobClient() *client.JobClient {
	jenkinsCore := client.JenkinsCore{
		UserName: "rock",
		URL:      "http://172.20.7.199:8088",
		Token:    "rock****",
	}
        return &client.JobClient{
		JenkinsCore: jenkinsCore,
	}
}


func GetJob(jobName string) {
	jenkinsJobCli := NewJenkinsJobClient()
	job, err := jenkinsJobCli.GetJob(jobName)
        // ... ...
}

func BuildJob(jobName string) {
	jenkinsJobCli := NewJenkinsJobClient()
	params := []client.ParameterDefinition{
		{
			Name:  "app_name",
			Value: "xxxx",
		},
		{
			Name:  "gitlab_address",
			Value: "http://gitlab.xxx.com/xxx/xxx.git",
		},
		{
			Name:  "branch",
			Value: "master",
		},
	}

	err := jenkinsJobCli.BuildWithParams(jobName, params)
	if err != nil {
		fmt.Println("[error] BuildWithParams err: ", err)
	} else {
		fmt.Println("[info] BuildWithParams success")
	}
}
```
2. when I execute GetJob func, return many job infomation.
3. but, when I execute BuildJob func, return an error: "the current user has not permission, code 403"

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38550412/126125383-208b6a75-6f90-41fe-b30a-8babd6efb299.png)

**Comment by LinuxSuRen** [comment]
Are you trying to use this project as a Jenkins client library? And what's version of your Jenkins?

**Comment by rockwang465** [comment]
Currently my Jenkins permission is admin.  
If I use an incorrect password, then GetJob func will return an error .

**Comment by rockwang465** [comment]
> Are you trying to use this project as a Jenkins client library? And what's version of your Jenkins?
I just want to use ``jenkins-zh/jenkins-cli`` as my Golang API, to build/get Jenkins job. 
My jenkins version is 2.227

**Comment by rockwang465** [comment]
```
func BuildJob(jobName string) {
	jenkinsJobCli := NewJenkinsJobClient()
	params := []client.ParameterDefinition{
		{
			Name:  "app_name",
			Value: "xxxx",
		},
		{
			Name:  "gitlab_address",
			Value: "http://gitlab.xxx.com/xxx/xxx.git",
		},
		{
			Name:  "branch",
			Value: "master",
		},
	}
}
```
Are my input parameters wrong?

**Comment by rockwang465** [comment]
> Are you trying to use this project as a Jenkins client library? And what's version of your Jenkins?

看到你是中国的，可以加下qq问下吗？ 
我QQ 1031653788。
感谢！

**Comment by LinuxSuRen** [comment]
I guess the problem comes from [here](https://github.com/jenkinsci/jenkins/commit/772152315aa0a9ba27b812a4ba0f3f9b64af78d9). Please try to add the following environment variables. See also [here](https://github.com/kubesphere/ks-jenkins/blob/2efd10d6088710df2c209be18a326732eb1694da/formula.yaml#L618).

`hudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true`

**Comment by rockwang465** [comment]
the golang code,  I don't know where the definition is.

**Comment by rockwang465** [comment]
Thank you. This issue has been resolved by installing the 'Strict Crumb Issuer Plugin`.
![image](https://user-images.githubusercontent.com/38550412/126133931-2439999d-54c6-4954-bb47-da46f46939ec.png)

**Comment by LinuxSuRen** [comment]
That's good news. I guess we can close this issue.

/close

**Comment by B1ackg0d** [comment]
> Thank you. This issue has been resolved by installing the 'Strict Crumb Issuer Plugin`. ![image](https://user-images.githubusercontent.com/38550412/126133931-2439999d-54c6-4954-bb47-da46f46939ec.png)

I have the same problem. According to what was said above, I downloaded this plugin and restarted, but it doesn't seem to solve this problem. Do I need to set anything else?
![image](https://github.com/jenkins-zh/jenkins-cli/assets/50610732/76cb0b39-c609-4da4-ab88-48615afb9a15)

**Comment by LinuxSuRen** [comment]
What the version of your Jenkins is?

**Comment by B1ackg0d** [comment]
> What the version of your Jenkins is?

Jenkins 2.429

**Comment by B1ackg0d** [comment]
![image](https://github.com/jenkins-zh/jenkins-cli/assets/50610732/69b777fa-8370-493e-b631-088b52c32481)
I fixed it, we need to set the cookie first after the new version. This cookie is from the crumbIssuer response header [key:Set-Cookie,Val:JSESSIONID]

**Comment by LinuxSuRen** [comment]
Thanks for your answer. Please feel free to help us to fix it in this project if you want.
