### ISSUE TITLE
job的create、edit、type不好用，具体报错信息如下

### ISSUE THREAD

**Issue by love574** [jenkins-zh/jenkins-cli#78]
jcli的版本为：v0.0.16
![image](https://user-images.githubusercontent.com/23184352/61938003-b6fc1200-afc2-11e9-9048-a96f7a55c9fc.png)
![image](https://user-images.githubusercontent.com/23184352/61938090-d8f59480-afc2-11e9-9540-93f17da88daf.png)
![image](https://user-images.githubusercontent.com/23184352/61938110-e6ab1a00-afc2-11e9-8185-67b1b900ae68.png)

**Comment by LinuxSuRen** [comment]
For `jcli job create job3` there are no errors found in v0.0.20.

**Comment by LinuxSuRen** [comment]
All issues should be fixed.
